print("Hello World")
print("Alas, poor yorrick")
print("Alas, poor yorrick")
print("Alas, poor yorrick")
print("Alas, poor yorrick")
print("Alas, poor yorrick")
print("Alas, poor yorrick")
print("Alas, poor yorrick")
print("Alas, poor yorrick")
print("Alas, poor yorrick")
print("Alas, poor yorrick")
print("Alas, poor yorrick")
print("Alas, poor yorrick")
print("Goodbye world")